# Generated by Django 5.1.1 on 2024-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.CharField(max_length=40, unique=True)),
                ('style_desc', models.TextField(max_length=400)),
                ('mini_market', models.FileField(upload_to='mini_market')),
                ('techpack', models.FileField(upload_to='techpack')),
                ('composition', models.FileField(upload_to='composition')),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('fabric_name', models.TextField(max_length=200)),
                ('fabric_consumption', models.TextField(max_length=200)),
                ('fabric_cost', models.CharField(max_length=20)),
                ('accessories_name', models.TextField(max_length=300)),
                ('accessories_consumption', models.TextField(max_length=300)),
                ('accessories_cost', models.CharField(max_length=20)),
                ('wash_plant_name', models.TextField(max_length=200)),
                ('wash_cost', models.CharField(max_length=20)),
            ],
        ),
    ]
