# Generated by Django 5.1.1 on 2024-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='accessories_consumption',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='styles',
            name='accessories_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='styles',
            name='composition',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='enquiry_date',
            field=models.DateTimeField(verbose_name='Enquirey Date'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='fabric_consumption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='styles',
            name='fabric_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='styles',
            name='mini_market',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='style_desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='styles',
            name='techpack',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='wash_plant_name',
            field=models.CharField(max_length=200),
        ),
    ]
