# Generated by Django 5.1.1 on 2024-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_styles_accessories_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='composition',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='mini_market',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='techpack',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='documents/'),
        ),
    ]
