# Generated by Django 5.1.1 on 2024-10-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_styles_composition_alter_styles_mini_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='accessories_consumption',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='accessories_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='accessories_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='composition',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='enquiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enquirey Date'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='fabric_consumption',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='fabric_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='fabric_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='mini_market',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='style_no',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='techpack',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='wash_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
