# Generated by Django 4.2 on 2024-10-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_styles_accessories_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forenKey', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.styles')),
            ],
        ),
    ]
