# Generated by Django 4.2 on 2024-10-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_requisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='forenKey',
            new_name='styles',
        ),
    ]
