# Generated by Django 4.2 on 2024-10-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_forenkey_requisition_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='styles',
            field=models.ForeignKey(default='---Select---', on_delete=django.db.models.deletion.CASCADE, to='app.styles'),
        ),
    ]
